# Generated by Django 5.1.7 on 2025-03-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='version',
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
